# Generated by Django 3.2.5 on 2021-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('fastingFood', models.BooleanField(blank=True)),
            ],
        ),
    ]
